# Generated by Django 5.1.6 on 2025-04-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketingStatus',
            new_name='TicketStatus',
        ),
        migrations.DeleteModel(
            name='TicketingProfile',
        ),
    ]
