# Generated by Django 5.1.6 on 2025-04-20 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0002_rename_ticketingstatus_ticketstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing_system.ticketstatus'),
        ),
    ]
