# Generated by Django 5.1.6 on 2025-04-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='logged_by',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_logged',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='automated',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='time_logged',
        ),
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing_system.organization'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
