# Generated by Django 5.1.6 on 2025-04-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0004_organization_remove_ticket_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='organization',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
