# Generated by Django 5.1.6 on 2025-04-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0005_alter_ticket_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
