# Generated by Django 5.1.6 on 2025-04-12 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_status_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='pwn', max_length=28),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
