# Generated by Django 5.1.6 on 2025-04-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_receiver_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
