# Generated by Django 5.1.6 on 2025-04-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_privatemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
