# Generated by Django 5.1.6 on 2025-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='open', max_length=32),
        ),
    ]
