# Generated by Django 5.1.6 on 2025-04-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
